/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as StudentTimetableRouteImport } from './routes/student/timetable'
import { Route as StudentPerformanceRouteImport } from './routes/student/performance'
import { Route as StudentMaterialsRouteImport } from './routes/student/materials'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentAttendanceRouteImport } from './routes/student/attendance'
import { Route as StudentAssignmentsRouteImport } from './routes/student/assignments'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ParentMessagesRouteImport } from './routes/parent/messages'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as FacultyMessagesRouteImport } from './routes/faculty/messages'
import { Route as FacultyDashboardRouteImport } from './routes/faculty/dashboard'
import { Route as FacultyAttendanceRouteImport } from './routes/faculty/attendance'
import { Route as FacultyAssignmentsRouteImport } from './routes/faculty/assignments'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ParentChildChildIdRouteImport } from './routes/parent/child.$childId'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPerformanceRoute = StudentPerformanceRouteImport.update({
  id: '/student/performance',
  path: '/student/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/student/materials',
  path: '/student/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/parent/messages',
  path: '/parent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyMessagesRoute = FacultyMessagesRouteImport.update({
  id: '/faculty/messages',
  path: '/faculty/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyAttendanceRoute = FacultyAttendanceRouteImport.update({
  id: '/faculty/attendance',
  path: '/faculty/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyAssignmentsRoute = FacultyAssignmentsRouteImport.update({
  id: '/faculty/assignments',
  path: '/faculty/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildChildIdRoute = ParentChildChildIdRouteImport.update({
  id: '/parent/child/$childId',
  path: '/parent/child/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/messages': typeof FacultyMessagesRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/messages': typeof FacultyMessagesRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/messages': typeof FacultyMessagesRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/parent/child/$childId': typeof ParentChildChildIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/dashboard'
    | '/faculty/messages'
    | '/parent/dashboard'
    | '/parent/messages'
    | '/posts/$postId'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/materials'
    | '/student/performance'
    | '/student/timetable'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/public/cron'
    | '/api/users/$userId'
    | '/parent/child/$childId'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/profile'
    | '/redirect'
    | '/api/users'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/dashboard'
    | '/faculty/messages'
    | '/parent/dashboard'
    | '/parent/messages'
    | '/posts/$postId'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/materials'
    | '/student/performance'
    | '/student/timetable'
    | '/users/$userId'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/public/cron'
    | '/api/users/$userId'
    | '/parent/child/$childId'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/customScript.js'
    | '/deferred'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/dashboard'
    | '/faculty/messages'
    | '/parent/dashboard'
    | '/parent/messages'
    | '/posts/$postId'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/materials'
    | '/student/performance'
    | '/student/timetable'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/public/cron'
    | '/api/users/$userId'
    | '/parent/child/$childId'
    | '/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  FacultyAssignmentsRoute: typeof FacultyAssignmentsRoute
  FacultyAttendanceRoute: typeof FacultyAttendanceRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyMessagesRoute: typeof FacultyMessagesRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentPerformanceRoute: typeof StudentPerformanceRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
  ParentChildChildIdRoute: typeof ParentChildChildIdRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/performance': {
      id: '/student/performance'
      path: '/student/performance'
      fullPath: '/student/performance'
      preLoaderRoute: typeof StudentPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/student/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/parent/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/messages': {
      id: '/faculty/messages'
      path: '/faculty/messages'
      fullPath: '/faculty/messages'
      preLoaderRoute: typeof FacultyMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/attendance': {
      id: '/faculty/attendance'
      path: '/faculty/attendance'
      fullPath: '/faculty/attendance'
      preLoaderRoute: typeof FacultyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/assignments': {
      id: '/faculty/assignments'
      path: '/faculty/assignments'
      fullPath: '/faculty/assignments'
      preLoaderRoute: typeof FacultyAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/child/$childId': {
      id: '/parent/child/$childId'
      path: '/parent/child/$childId'
      fullPath: '/parent/child/$childId'
      preLoaderRoute: typeof ParentChildChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  FacultyAssignmentsRoute: FacultyAssignmentsRoute,
  FacultyAttendanceRoute: FacultyAttendanceRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyMessagesRoute: FacultyMessagesRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentPerformanceRoute: StudentPerformanceRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
  ParentChildChildIdRoute: ParentChildChildIdRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
